[package]
name = "mimo-agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
mimo-client = { path = "../mimo-client" }
mimo-protocol = { path = "../mimo-protocol" }
mimo-tools = { path = "../mimo-tools" }
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
